// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	MNproduct "github.com/777continue/gomall/app/frontend/biz/router/MNproduct"
	auth "github.com/777continue/gomall/app/frontend/biz/router/auth"
	cart "github.com/777continue/gomall/app/frontend/biz/router/cart"
	category "github.com/777continue/gomall/app/frontend/biz/router/category"
	checkout "github.com/777continue/gomall/app/frontend/biz/router/checkout"

	home "github.com/777continue/gomall/app/frontend/biz/router/home"
	order "github.com/777continue/gomall/app/frontend/biz/router/order"
	product "github.com/777continue/gomall/app/frontend/biz/router/product"
	user "github.com/777continue/gomall/app/frontend/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	MNproduct.Register(r)

	user.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	category.Register(r)

	product.Register(r)

	auth.Register(r)

	home.Register(r)
}
