CREATE DATABASE IF NOT EXISTS demo;
CREATE DATABASE IF NOT EXISTS user;

CREATE DATABASE IF NOT EXISTS product;

CREATE DATABASE IF NOT EXISTS cart;

CREATE DATABASE IF NOT EXISTS payment;

CREATE DATABASE IF NOT EXISTS `order`;
-- DATABASE CREATED 
