// Code generated by hertz generator.

package home

import (
	"context"

	home "github.com/777continue/gomall/app/frontend/biz/handler/home"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/sessions"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			s := sessions.Default(c)
			ctx = context.WithValue(ctx, home.SessionUserId, s.Get("user_id"))
			c.Next(ctx)
		},
	}
}

func _homeMw() []app.HandlerFunc {
	// your code...
	return nil
}
